import yaml
import glob
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("-r", "--rulesdirectory", help="Sub-directory generated by rules-search", required=True, type=str)
parser.add_argument("-f", "--fileext", help="Rule file extension", default="yml", type=str)
parser.add_argument("--oneline", help="Put all tags on a single line", action="store_true")
args = parser.parse_args()

files = glob.glob(args.rulesdirectory + "/**/*." + args.fileext, recursive=True)

for file in files:
    d={}
    with open(file, 'r') as stream:
        docs = yaml.load_all(stream, Loader=yaml.FullLoader)
        for doc in docs:
            for k,v in doc.items():
                if k in ['title','description','tags','level','author']:
                    d[k]=v
        if args.oneline:
            expandTags = ",".join([ tag for tags in d["tags"] if "attack" in tag ])
            print(f'{d["title"]},{d["description"]},{expandTags}')
        else: 
            if "tags" in d:
                for tag in d["tags"]:
                    if "attack" in tag:
                        print(f'{d["title"]},{d["description"]},{tag}')